apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-demo-production
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    demo-environment: production
  annotations:
    codefresh.io/product: guestbook-demo
spec:
  project: default
  destination:
    name: in-cluster
    namespace: cf-guestbook-demo-production
  source:
    path: guestbook-demo/helm-guestbook-prod
    repoURL: https://github.com/idan-codefresh/gitops-cloud-demo-project.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
